package com.homeaccounting.mapper;

import com.homeaccounting.entity.AcctTransaction;
import com.homeaccounting.entity.AcctTransactionExample;
import java.time.LocalDateTime;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AcctTransactionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactions
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    long countByExample(AcctTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactions
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int deleteByExample(AcctTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactions
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactions
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int insert(AcctTransaction row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactions
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int insertSelective(AcctTransaction row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactions
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    List<AcctTransaction> selectByExample(AcctTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactions
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    AcctTransaction selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactions
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int updateByExampleSelective(@Param("row") AcctTransaction row, @Param("example") AcctTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactions
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int updateByExample(@Param("row") AcctTransaction row, @Param("example") AcctTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactions
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int updateByPrimaryKeySelective(AcctTransaction row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactions
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int updateByPrimaryKey(AcctTransaction row);

  List<AcctTransaction> selectHouseholdLedgerLimited(
      @Param("householdId") long householdId,
      @Param("ledgerId") Long ledgerId,
      @Param("fundAccountId") Long fundAccountId,
      @Param("occurredFrom") LocalDateTime occurredFrom,
      @Param("occurredTo") LocalDateTime occurredTo,
      @Param("limit") int limit);
}