package com.homeaccounting.mapper;

import com.homeaccounting.entity.FundAccount;
import com.homeaccounting.entity.FundAccountExample;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FundAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_accounts
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    long countByExample(FundAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_accounts
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int deleteByExample(FundAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_accounts
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_accounts
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int insert(FundAccount row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_accounts
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int insertSelective(FundAccount row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_accounts
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    List<FundAccount> selectByExample(FundAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_accounts
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    FundAccount selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_accounts
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int updateByExampleSelective(@Param("row") FundAccount row, @Param("example") FundAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_accounts
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int updateByExample(@Param("row") FundAccount row, @Param("example") FundAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_accounts
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int updateByPrimaryKeySelective(FundAccount row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_accounts
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int updateByPrimaryKey(FundAccount row);

  /** CAS：version 不匹配时返回 0 */
  int updateBalanceOptimistic(
      @Param("id") Long id,
      @Param("householdId") Long householdId,
      @Param("expectedVersion") Long expectedVersion,
      @Param("newBalance") BigDecimal newBalance,
      @Param("newVersion") Long newVersion,
      @Param("updatedAt") LocalDateTime updatedAt);
}