package com.homeaccounting.mapper;

import com.homeaccounting.entity.HouseholdMember;
import com.homeaccounting.entity.HouseholdMemberExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HouseholdMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household_members
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    long countByExample(HouseholdMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household_members
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int deleteByExample(HouseholdMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household_members
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household_members
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int insert(HouseholdMember row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household_members
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int insertSelective(HouseholdMember row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household_members
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    List<HouseholdMember> selectByExample(HouseholdMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household_members
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    HouseholdMember selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household_members
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int updateByExampleSelective(@Param("row") HouseholdMember row, @Param("example") HouseholdMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household_members
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int updateByExample(@Param("row") HouseholdMember row, @Param("example") HouseholdMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household_members
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int updateByPrimaryKeySelective(HouseholdMember row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household_members
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int updateByPrimaryKey(HouseholdMember row);
}