package com.homeaccounting.mapper;

import com.homeaccounting.entity.Household;
import com.homeaccounting.entity.HouseholdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HouseholdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table households
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    long countByExample(HouseholdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table households
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int deleteByExample(HouseholdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table households
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table households
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int insert(Household row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table households
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int insertSelective(Household row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table households
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    List<Household> selectByExample(HouseholdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table households
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    Household selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table households
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int updateByExampleSelective(@Param("row") Household row, @Param("example") HouseholdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table households
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int updateByExample(@Param("row") Household row, @Param("example") HouseholdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table households
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int updateByPrimaryKeySelective(Household row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table households
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int updateByPrimaryKey(Household row);
}