package com.homeaccounting.mapper;

import com.homeaccounting.entity.Ledger;
import com.homeaccounting.entity.LedgerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LedgerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledgers
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    long countByExample(LedgerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledgers
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int deleteByExample(LedgerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledgers
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledgers
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int insert(Ledger row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledgers
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int insertSelective(Ledger row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledgers
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    List<Ledger> selectByExample(LedgerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledgers
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    Ledger selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledgers
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int updateByExampleSelective(@Param("row") Ledger row, @Param("example") LedgerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledgers
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int updateByExample(@Param("row") Ledger row, @Param("example") LedgerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledgers
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int updateByPrimaryKeySelective(Ledger row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledgers
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int updateByPrimaryKey(Ledger row);
}