package com.homeaccounting.mapper;

import com.homeaccounting.entity.Tag;
import com.homeaccounting.entity.TagExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    long countByExample(TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int deleteByExample(TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int insert(Tag row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int insertSelective(Tag row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    List<Tag> selectByExample(TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    Tag selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int updateByExampleSelective(@Param("row") Tag row, @Param("example") TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int updateByExample(@Param("row") Tag row, @Param("example") TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int updateByPrimaryKeySelective(Tag row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int updateByPrimaryKey(Tag row);
}