package com.homeaccounting.mapper;

import com.homeaccounting.entity.TransactionTag;
import com.homeaccounting.entity.TransactionTagExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TransactionTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_tags
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    long countByExample(TransactionTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_tags
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int deleteByExample(TransactionTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_tags
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int deleteByPrimaryKey(@Param("transactionId") Long transactionId, @Param("tagId") Long tagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_tags
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int insert(TransactionTag row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_tags
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int insertSelective(TransactionTag row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_tags
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    List<TransactionTag> selectByExample(TransactionTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_tags
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int updateByExampleSelective(@Param("row") TransactionTag row, @Param("example") TransactionTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_tags
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    int updateByExample(@Param("row") TransactionTag row, @Param("example") TransactionTagExample example);
}