package com.homeaccounting.entity;

import java.math.BigDecimal;
import java.time.LocalDateTime;

public class AcctTransaction {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactions.id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactions.household_id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private Long householdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactions.ledger_id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private Long ledgerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactions.fund_account_id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private Long fundAccountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactions.category_id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private Long categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactions.type
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactions.amount
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactions.occurred_at
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private LocalDateTime occurredAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactions.note
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactions.created_by
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private Long createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactions.created_at
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactions.updated_at
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private LocalDateTime updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactions.id
     *
     * @return the value of transactions.id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactions.id
     *
     * @param id the value for transactions.id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactions.household_id
     *
     * @return the value of transactions.household_id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public Long getHouseholdId() {
        return householdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactions.household_id
     *
     * @param householdId the value for transactions.household_id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setHouseholdId(Long householdId) {
        this.householdId = householdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactions.ledger_id
     *
     * @return the value of transactions.ledger_id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public Long getLedgerId() {
        return ledgerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactions.ledger_id
     *
     * @param ledgerId the value for transactions.ledger_id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setLedgerId(Long ledgerId) {
        this.ledgerId = ledgerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactions.fund_account_id
     *
     * @return the value of transactions.fund_account_id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public Long getFundAccountId() {
        return fundAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactions.fund_account_id
     *
     * @param fundAccountId the value for transactions.fund_account_id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setFundAccountId(Long fundAccountId) {
        this.fundAccountId = fundAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactions.category_id
     *
     * @return the value of transactions.category_id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactions.category_id
     *
     * @param categoryId the value for transactions.category_id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactions.type
     *
     * @return the value of transactions.type
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactions.type
     *
     * @param type the value for transactions.type
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactions.amount
     *
     * @return the value of transactions.amount
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactions.amount
     *
     * @param amount the value for transactions.amount
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactions.occurred_at
     *
     * @return the value of transactions.occurred_at
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public LocalDateTime getOccurredAt() {
        return occurredAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactions.occurred_at
     *
     * @param occurredAt the value for transactions.occurred_at
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setOccurredAt(LocalDateTime occurredAt) {
        this.occurredAt = occurredAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactions.note
     *
     * @return the value of transactions.note
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactions.note
     *
     * @param note the value for transactions.note
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactions.created_by
     *
     * @return the value of transactions.created_by
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactions.created_by
     *
     * @param createdBy the value for transactions.created_by
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactions.created_at
     *
     * @return the value of transactions.created_at
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactions.created_at
     *
     * @param createdAt the value for transactions.created_at
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactions.updated_at
     *
     * @return the value of transactions.updated_at
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactions.updated_at
     *
     * @param updatedAt the value for transactions.updated_at
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}