package com.homeaccounting.entity;

import java.time.LocalDateTime;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.household_id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private Long householdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.type
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.name
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.sort_order
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private Integer sortOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.enabled
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private Boolean enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.created_at
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.updated_at
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private LocalDateTime updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.id
     *
     * @return the value of categories.id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.id
     *
     * @param id the value for categories.id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.household_id
     *
     * @return the value of categories.household_id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public Long getHouseholdId() {
        return householdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.household_id
     *
     * @param householdId the value for categories.household_id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setHouseholdId(Long householdId) {
        this.householdId = householdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.type
     *
     * @return the value of categories.type
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.type
     *
     * @param type the value for categories.type
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.name
     *
     * @return the value of categories.name
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.name
     *
     * @param name the value for categories.name
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.sort_order
     *
     * @return the value of categories.sort_order
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.sort_order
     *
     * @param sortOrder the value for categories.sort_order
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.enabled
     *
     * @return the value of categories.enabled
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.enabled
     *
     * @param enabled the value for categories.enabled
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.created_at
     *
     * @return the value of categories.created_at
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.created_at
     *
     * @param createdAt the value for categories.created_at
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.updated_at
     *
     * @return the value of categories.updated_at
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.updated_at
     *
     * @param updatedAt the value for categories.updated_at
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}