package com.homeaccounting.entity;

import java.math.BigDecimal;
import java.time.LocalDateTime;

public class FundAccount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_accounts.id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_accounts.household_id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private Long householdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_accounts.name
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_accounts.balance
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private BigDecimal balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_accounts.version
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_accounts.created_at
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_accounts.updated_at
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private LocalDateTime updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_accounts.id
     *
     * @return the value of fund_accounts.id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_accounts.id
     *
     * @param id the value for fund_accounts.id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_accounts.household_id
     *
     * @return the value of fund_accounts.household_id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public Long getHouseholdId() {
        return householdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_accounts.household_id
     *
     * @param householdId the value for fund_accounts.household_id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setHouseholdId(Long householdId) {
        this.householdId = householdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_accounts.name
     *
     * @return the value of fund_accounts.name
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_accounts.name
     *
     * @param name the value for fund_accounts.name
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_accounts.balance
     *
     * @return the value of fund_accounts.balance
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_accounts.balance
     *
     * @param balance the value for fund_accounts.balance
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_accounts.version
     *
     * @return the value of fund_accounts.version
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_accounts.version
     *
     * @param version the value for fund_accounts.version
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_accounts.created_at
     *
     * @return the value of fund_accounts.created_at
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_accounts.created_at
     *
     * @param createdAt the value for fund_accounts.created_at
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_accounts.updated_at
     *
     * @return the value of fund_accounts.updated_at
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_accounts.updated_at
     *
     * @param updatedAt the value for fund_accounts.updated_at
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}