package com.homeaccounting.entity;

import java.time.LocalDateTime;

public class Household {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column households.id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column households.name
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column households.invite_code
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private String inviteCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column households.created_at
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private LocalDateTime createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column households.id
     *
     * @return the value of households.id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column households.id
     *
     * @param id the value for households.id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column households.name
     *
     * @return the value of households.name
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column households.name
     *
     * @param name the value for households.name
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column households.invite_code
     *
     * @return the value of households.invite_code
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public String getInviteCode() {
        return inviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column households.invite_code
     *
     * @param inviteCode the value for households.invite_code
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setInviteCode(String inviteCode) {
        this.inviteCode = inviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column households.created_at
     *
     * @return the value of households.created_at
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column households.created_at
     *
     * @param createdAt the value for households.created_at
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}