package com.homeaccounting.entity;

import java.time.LocalDateTime;

public class HouseholdMember {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column household_members.id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column household_members.household_id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private Long householdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column household_members.user_id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column household_members.role
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column household_members.joined_at
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private LocalDateTime joinedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column household_members.id
     *
     * @return the value of household_members.id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column household_members.id
     *
     * @param id the value for household_members.id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column household_members.household_id
     *
     * @return the value of household_members.household_id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public Long getHouseholdId() {
        return householdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column household_members.household_id
     *
     * @param householdId the value for household_members.household_id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setHouseholdId(Long householdId) {
        this.householdId = householdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column household_members.user_id
     *
     * @return the value of household_members.user_id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column household_members.user_id
     *
     * @param userId the value for household_members.user_id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column household_members.role
     *
     * @return the value of household_members.role
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column household_members.role
     *
     * @param role the value for household_members.role
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column household_members.joined_at
     *
     * @return the value of household_members.joined_at
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public LocalDateTime getJoinedAt() {
        return joinedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column household_members.joined_at
     *
     * @param joinedAt the value for household_members.joined_at
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setJoinedAt(LocalDateTime joinedAt) {
        this.joinedAt = joinedAt;
    }
}