package com.homeaccounting.entity;

import java.time.LocalDateTime;

public class Tag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.household_id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private Long householdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.name
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.created_at
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.updated_at
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private LocalDateTime updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.id
     *
     * @return the value of tags.id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.id
     *
     * @param id the value for tags.id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.household_id
     *
     * @return the value of tags.household_id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public Long getHouseholdId() {
        return householdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.household_id
     *
     * @param householdId the value for tags.household_id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setHouseholdId(Long householdId) {
        this.householdId = householdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.name
     *
     * @return the value of tags.name
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.name
     *
     * @param name the value for tags.name
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.created_at
     *
     * @return the value of tags.created_at
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.created_at
     *
     * @param createdAt the value for tags.created_at
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.updated_at
     *
     * @return the value of tags.updated_at
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.updated_at
     *
     * @param updatedAt the value for tags.updated_at
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}