package com.homeaccounting.entity;

public class TransactionTag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_tags.transaction_id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private Long transactionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_tags.tag_id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private Long tagId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_tags.transaction_id
     *
     * @return the value of transaction_tags.transaction_id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public Long getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_tags.transaction_id
     *
     * @param transactionId the value for transaction_tags.transaction_id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setTransactionId(Long transactionId) {
        this.transactionId = transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_tags.tag_id
     *
     * @return the value of transaction_tags.tag_id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public Long getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_tags.tag_id
     *
     * @param tagId the value for transaction_tags.tag_id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setTagId(Long tagId) {
        this.tagId = tagId;
    }
}