package com.homeaccounting.entity;

import java.time.LocalDateTime;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.wechat_openid
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private String wechatOpenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.wechat_unionid
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private String wechatUnionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.nickname
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.avatar_url
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private String avatarUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.created_at
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.updated_at
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    private LocalDateTime updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.id
     *
     * @return the value of users.id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.id
     *
     * @param id the value for users.id
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.wechat_openid
     *
     * @return the value of users.wechat_openid
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public String getWechatOpenid() {
        return wechatOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.wechat_openid
     *
     * @param wechatOpenid the value for users.wechat_openid
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setWechatOpenid(String wechatOpenid) {
        this.wechatOpenid = wechatOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.wechat_unionid
     *
     * @return the value of users.wechat_unionid
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public String getWechatUnionid() {
        return wechatUnionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.wechat_unionid
     *
     * @param wechatUnionid the value for users.wechat_unionid
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setWechatUnionid(String wechatUnionid) {
        this.wechatUnionid = wechatUnionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.nickname
     *
     * @return the value of users.nickname
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.nickname
     *
     * @param nickname the value for users.nickname
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.avatar_url
     *
     * @return the value of users.avatar_url
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.avatar_url
     *
     * @param avatarUrl the value for users.avatar_url
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.created_at
     *
     * @return the value of users.created_at
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.created_at
     *
     * @param createdAt the value for users.created_at
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.updated_at
     *
     * @return the value of users.updated_at
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.updated_at
     *
     * @param updatedAt the value for users.updated_at
     *
     * @mbg.generated Mon May 04 21:20:18 SGT 2026
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}